{{- if .Values.cloudflare.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflare-gateway-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.cloudflare.apiToken | quote }}
  account-id: {{ .Values.cloudflare.accountId | quote }}
{{- end }}
